### ISSUE TITLE
Implement chat window in task session

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/client#87]
- [x] sopra-fs22-group-23/client#88
- [x] sopra-fs22-group-23/client#89
- [x] sopra-fs22-group-23/client#90
- [x] sopra-fs22-group-23/client#91
- [x] sopra-fs22-group-23/server#140
- [x] sopra-fs22-group-23/server#142
